workspace_name: "agentic"
workspace_path: "/Users/jakobgrant/Workspaces/agentic"
analysis_depth: standard
auto_spawn_agents: true
default_agents:
  - claude_code
max_concurrent_agents: 3
include_tests: true
include_docs: true
log_level: INFO
ignore_patterns:
  - "*.pyc"
  - "__pycache__"
  - ".git"
  - "node_modules"
  - "*.log"
  - ".DS_Store"
  - "*.tmp"
  - "*.temp"

# API Configuration (if environment variables are set)
