agents: {}
analysis_depth: standard
auto_spawn_agents: true
default_agents:
- claude_code
ignore_patterns:
- '*.pyc'
- __pycache__
- .git
- node_modules
- '*.log'
- .DS_Store
- '*.tmp'
- '*.temp'
include_docs: true
include_tests: true
log_file: null
log_level: INFO
max_concurrent_agents: 3
workspace_name: agentic
workspace_path: /Users/jakobgrant/Workspaces/agentic
